core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Todo API",
        default_version="v1",
        description="todo app for github",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="shayanpars230@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('', include('accounts.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

core/todo/api/v1/urls.py
from rest_framework.routers import SimpleRouter, DefaultRouter
from django.urls import path
from .views import TaskViewSet

app_name = 'api-v1'

router = DefaultRouter()
router.register('task', TaskViewSet, basename='task')
urlpatterns = router.urls

core/todo/urls.py
from django.urls import path, include
from . import views

app_name = 'task'

urlpatterns = [
    path('', views.TaskApiView.as_view(), name='task-api'),
    path('task', views.TaskList.as_view(), name='task-list'),
    path('task/add', views.TaskCreate.as_view(), name='create-task'),
    path('delete/<int:pk>', views.TaskDelete.as_view(), name='delete-task'),
    path('complete/<int:pk>', views.TaskComplete.as_view(), name='complete-task'),
    path('update/<int:pk>', views.TaskUpdate.as_view(), name='update-task'),
    path("api/v1/", include("todo.api.v1.urls")),
]

core/todo/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    'create a model for todo app'
    
    title = models.CharField(max_length=245)
    body = models.TextField(default='', null=True, blank=True)
    done = models.BooleanField(default=False,)
    def __str__(self):
        return self.title

core/todo/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields='__all__'

core/todo/api/v1/views.py
from ...models import Todo
from .serializers import TaskSerializer
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
class TaskViewSet(viewsets.ModelViewSet):
    """
    A simple ViewSet for viewing and editing accounts.
    """
    queryset = Todo.objects.all()
    serializer_class = TaskSerializer
    permission_classes = [IsAuthenticated]

core/todo/views.py
from typing import Any
from django.http import HttpRequest
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.views.generic import  ListView, TemplateView
from .models import Todo
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class TaskList(LoginRequiredMixin, ListView):
    model = Todo


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Todo
    fields = ['title']
    success_url  = reverse_lazy('task:task-list')
   
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate,self).form_valid(form)
    
    

class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Todo
    success_url = reverse_lazy('task:task-list')


    def get(self, request: HttpRequest, *args: Any, **kwargs: Any):
        return self.post(request, *args, **kwargs)
    def get_queryset(self):
        return self.model.objects.all()



class TaskComplete(LoginRequiredMixin, UpdateView):
    model = Todo    
    fields = [ 
        "done", 
    ] 
    success_url= reverse_lazy('task:task-list')

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any):
        object = self.model.objects.get(id=kwargs.get('pk'))
        object.done = True
        object.save()
        return redirect(self.success_url)
    


class TaskUpdate(UpdateView):
    model = Todo    
    fields = [ 
        "title", 
    ]
    template_name = 'todo/todo_update.html'
    success_url= reverse_lazy('task:task-list')

# api
    
class TaskApiView(TemplateView):
    template_name = "api/index.html"

core/templates/todo/todo_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>task create</title>
</head>
<body>
    <div class="center">
        <form method="post" novalidate class="card">
            {%csrf_token %}
    
            <h2>Create Task</h2>
            
            {% for field in form %}
            {% if field.name == 'completed' %}
            <p>
                {{ field.label_tag }}
                {{ field }}
            </p>
            {% if field.errors %}
            <small class="error">{{ field.errors|striptags }}</small>
            {% endif %}
            {% else %}
            {{ field.label_tag }}
            {{ field }}
            {% if field.errors %}
            <small class="error">{{ field.errors|striptags }}</small>
            {% endif %}
            {% endif %}
            {% endfor %}
    
            <div class="form-buttons">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a href="{% url 'task:task-list' %}" class="btn btn-outline">Cancel</a>
            </div>
        </form>
    </div>
</body>
</html>

core/templates/todo/todo_list.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Ali Bigdeli">
    <meta name="generator" content="Hugo 0.88.1">
    <title>{% block title %} {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <style>
        body {
            width: 100%;
            height: 100vh;
            background: linear-gradient(to bottom, #e6e6e6 0%, #ffffff 100%);
        }
    </style>
    {% block extra_css %}{% endblock %}
</head>


<body>
    <form class="pt-3" method="POST" action="{% url 'task:create-task' %}">
        {% csrf_token %}
        <div class="input-group mb-3">
            <input type="text" class="form-control rounded-4" name="title" placeholder="Enter task title"
                aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-primary" type="submit">Add</button>
        </div>


        <hr class="my-4">
        {% for task in object_list %}
        <div class="input-group py-1">
            <span type="text" class="form-control" aria-label="Text input with segmented dropdown button">
                {% if task.done == True %}
                <strike>{{task.title}}</strike>
                {% else %}
                <span>{{task}}</span>
                {% endif %}
            </span>
            <a type="button" class="btn btn-danger" href="{% url 'task:delete-task' task.id %}"><i
                    class="bi bi-trash"></i>trash</a>
            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split"
                data-bs-toggle="dropdown" aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
                <li><a class="dropdown-item" href="{% url 'task:complete-task' task.id %}">Done</a></li>
                <li><a class="dropdown-item" href="{% url 'task:update-task' task.id %}">edit</a></li>
            </ul>
        </div>
        {% endfor %}
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>

</body>

</html>

core/templates/todo/todo_update.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Ali Bigdeli">
    <meta name="generator" content="Hugo 0.88.1">
    <title>{% block title %} {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <style>
        body {
            width: 100%;
            height: 100vh;
            background: linear-gradient(to bottom, #e6e6e6 0%, #ffffff 100%);
        }
    </style>
    {% block extra_css %}{% endblock %}
</head>

<body>

    <div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
        <div class="modal-dialog" role="document">
            <div class="modal-content rounded-5 shadow">
                <div class="modal-header p-5 pb-4 border-bottom-0">
                    <!-- <h5 class="modal-title">Modal title</h5> -->
                    <h2 class="fw-bold mb-0">Edit Form</h2>
                    <a type="button" class="btn-close" href="{% url 'task:task-list' %}"></a>
                </div>

                <div class="modal-body p-5 pt-0">

                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            {{form.title}}
                            <label for="floatingInput"></label>
                        </div>
                        <button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Change</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>

</body>

</html>